
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.print.DocFlavor;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ppp
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String tableindex=null;
    String roomname=null;
    String roomtype=null;
    public Rooms() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Update_table();
    }
    
    public void Update_table(){
        
        try{
            //Statement st=conn.createStatement();
            String sql="Select roomid,roomname,roomtypedesc,format(roomprice,2) as price from rooms,roomtype where rooms.roomtypeid=roomtype.roomtypeid;";
            
            //rs=st.executeQuery(sql); //if using simple query not prepared statment
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            tbl_rooms.setModel(DbUtils.resultSetToTableModel(rs));     
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);    
            
        } finally{
            try {
                rs.close();
                pst.close();
                                
            } catch (Exception e) {
            }
        }
        
    }
      
     
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rooms = new javax.swing.JTable();
        cmd_add = new javax.swing.JButton();
        cmd_edit = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        cmd_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_rooms.setFocusTraversalPolicyProvider(true);
        tbl_rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_roomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_rooms);

        cmd_add.setText("Add");
        cmd_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addActionPerformed(evt);
            }
        });

        cmd_edit.setText("Edit");
        cmd_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_editActionPerformed(evt);
            }
        });

        cmd_delete.setText("Delete");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_close.setText("Close");
        cmd_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmd_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_add, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(cmd_add)
                .addGap(18, 18, 18)
                .addComponent(cmd_edit)
                .addGap(18, 18, 18)
                .addComponent(cmd_delete)
                .addGap(18, 18, 18)
                .addComponent(cmd_close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-637)/2, (screenSize.height-478)/2, 637, 478);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmd_closeActionPerformed

    private void cmd_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new add_room().setVisible(true);
    }//GEN-LAST:event_cmd_addActionPerformed

    private void tbl_roomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_roomsMouseClicked
        // TODO add your handling code here:int row=tbl_roomtype.getSelectedRow();
        int row=tbl_rooms.getSelectedRow();
        String Table_click= (tbl_rooms.getModel().getValueAt(row, 0).toString());
        tableindex=Table_click;  
        roomname= (tbl_rooms.getModel().getValueAt(row, 1).toString());
        roomtype=(tbl_rooms.getModel().getValueAt(row, 2).toString());
        
    }//GEN-LAST:event_tbl_roomsMouseClicked

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            
        String sql="Delete from rooms where roomid=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, tableindex);
            pst.execute();
            Update_table();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
       
        
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_editActionPerformed
        // TODO add your handling code here:
        new edit_room(tableindex, roomname, roomtype).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cmd_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_add;
    private javax.swing.JButton cmd_close;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_rooms;
    // End of variables declaration//GEN-END:variables
}
